---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: private-registry
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
