---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: private-registry
spec:
  storageClassName: longhorn-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
